### ISSUE TITLE
please add ability to run some VE2 and VE3 voices

### ISSUE THREAD

**Issue by MuhammadGagah** [tsengwoody/WorldVoice#2]
Hi, I'm a WorldVoice user, and I really enjoy this add-on.
But I found a little problem, On VE2, WorldVoice can't run on some voices data, and for VE3, WorldVoice can't run for all voices data.
Please add supported all voices data for VE2, and also add VE3 support.
Thank you.

**Comment by tsengwoody** [comment]
WorldVoice only focuses on open source/free TTS engines and does not prioritize maintaining compatibility with thos commercial TTS engines.
