### ISSUE TITLE
SayAll is broken in NVDA Alpha.

### ISSUE THREAD

**Issue by cary-rowen** [tsengwoody/WorldVoice#20]
Using NVDA alpha-32997,3f82ab67 (2024.4.0.32997)

Use any of the following shortcut keys:
* `nvda+a`
* `nvda+shift+a`
* `nvda+b`

You will see the following error in the NVDA log:

```
Input: kb(laptop):NVDA+a
ERROR - scriptHandler.executeScript (22:55:56.514) - MainThread (13436):
error executing script: <bound method GlobalCommands.script_sayAll of <globalCommands.GlobalCommands object at 0x06A8EAF0>> with gesture 'NVDA+a'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 299, in executeScript
  File "globalCommands.pyc", line 2368, in script_sayAll
TypeError: _SayAllHandler.readText() got an unexpected keyword argument 'startedFromScript'
IO - inputCore.executeGesture (22:55:57.243) - winInputHook (9348):
Input: kb(laptop):NVDA+shift+control+f1
```

I'm guessing you monkey patched the sayAll function, This may be due to changes in [nvaccess/nvda/#16826](https://github.com/nvaccess/nvda/pull/16826) that exposed this issue

I don't think this is an API breaking change in this case, but is still worth bringing to the attention of add-on developers and PR authors.

cc @CyrilleB79 @tsengwoody

**Comment by lbk2907** [comment]
I wish I can help but I don't know how to code. If you know how to fix
this, maybe you can make a pull request for that.

**Comment by CyrilleB79** [comment]
Yes, very likely due to the introduction of https://github.com/nvaccess/nvda/pull/16826.

The say all code has been copied in this add-on. Since it has been modified in https://github.com/nvaccess/nvda/pull/16826, it should probably also be modified similarly in this add-on.

**Comment by lbk2907** [comment]
If you know how to make a pull request, you can do so. Do let me know if
you need any help in creating pull request.

**Comment by CyrilleB79** [comment]
@lbk2907, I have not investigated in detail the code and I do not plan to do so. I am not a user of this add-on.

I am the author of https://github.com/nvaccess/nvda/pull/16826.
@tsengwoody or whoever want to fix this issue can have a look to https://github.com/nvaccess/nvda/pull/16826.
If needed, I am available to provide further information to someone wanting to write a fix. But I doubt it will be necessary, since https://github.com/nvaccess/nvda/pull/16826 is not so big.

**Comment by tsengwoody** [comment]
Fixed: commit 7a72e1
